name: Dev Calc API CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        required: false
        default: true
        description: Indicates whether the workflow should run the tests.
      run_lint:
        type: boolean
        required: false
        default: true
        description: Indicates whether the workflow should run the code style analyser.

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Maven project
        run: mvn clean install -DskipTests

  test:
    needs: build
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_tests: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true' }}
      run_lint: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_lint == 'true' }}

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Create package
        run: mvn clean package -DskipTests

  deploy-dev:
    runs-on: ubuntu-latest
    needs: package
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    environment:
      name: dev

    steps:
      - name: Deploy package
        run: |
          echo Preparando o deploy... Utilizando variável de dev: ${{ vars.DEV_ENV }}
          echo Criando o deploy... Utilizando segredo de dev: ${{ secrets.DEV_SECRET }}
          echo Deploy realizado com sucesso

  deploy-prod:
    runs-on: ubuntu-latest
    needs: package
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: prod

    steps:
      - name: Deploy package
        run: |
          echo Preparando o deploy... Utilizando variável de prod: ${{ vars.PROD_ENV }}
          echo Criando o deploy... Utilizando segredo de prod: ${{ secrets.PROD_SECRET }}
          echo Deploy realizado com sucesso
