name: Dev Calc API CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Maven project
        run: mvn clean install -DskipTests

  test:
    needs: build
    uses: ./.github/workflows/lint-and-test.yml

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Create package
        run: mvn clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Deploy package
        run: echo "Deploy realizado com sucesso"
