name: Dev Calc API CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        required: false
        default: true
        description: Indicates whether the workflow should run the tests.
      run_lint:
        type: boolean
        required: false
        default: true
        description: Indicates whether the workflow should run the code style analyser.

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Maven project
        run: mvn clean install -DskipTests

  test:
    needs: build
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_tests: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true' }}
      run_lint: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_lint == 'true' }}

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Create package
        run: mvn clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Deploy package
        run: echo "Deploy realizado com sucesso"
