name: Lint and Test
on:
  workflow_call:
    inputs:
      run_tests:
        type: boolean
        required: true
        description: Indicates whether the workflow should run the tests.
      run_lint:
        type: boolean
        required: true
        description: Indicates whether the workflow should run the code style analyser.
jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run code style checker (lint)
        run: mvn clean checkstyle:check

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run tests
        run: mvn clean test