name: Variable Secret CI

on:
  workflow_dispatch:

jobs:
  variable-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show Variables
        run: |
          echo App mode: ${{ vars.APP_MODE }}
          echo Support email: ${{ vars.SUPPORT_EMAIL }}
      - name: Show Secret
        run : |
          echo Should not show the secret: ${{ secrets.PROD_TOKEN }}